In [1]:
import pandas as pd

In [6]:
dict_data = {
    'c0':[1,2,3],
    'c1':[4,5,6],
    'c2':[7,8,9],
    'c3':[10,11,12],
    'c4':[13,14,15]
}

df = pd.DataFrame(dict_data)

print(type(df))
print('\n')
print(df)

<class 'pandas.DataFrame'>


   c0  c1  c2  c3  c4
0   1   4   7  10  13
1   2   5   8  11  14
2   3   6   9  12  15

In [12]:
# pandes.Dataframe(2차원배열,
#                  index=행 인덱스 배열,
#                  columns=열 이름 배열)

arr = [
    [15,'남','덕영중'],
    [17,'여','수리중']
]

df = pd.DataFrame(arr,index=['준서','예은'],columns=['나이','성별','학교'])
print(df)

    나이 성별   학교
준서  15  남  덕영중
예은  17  여  수리중

In [1]:
import pandas as pd

arr = [
    [15,'남','덕영중'],
    [17,'여','수리중']
]

df = pd.DataFrame(arr,index=['준서','예은'],columns=['나이','성별','학교'])

print(df.index)
print(df.columns)

Index(['준서', '예은'], dtype='str')
Index(['나이', '성별', '학교'], dtype='str')

In [2]:
print(df)

    나이 성별   학교
준서  15  남  덕영중
예은  17  여  수리중

In [3]:
df.index = ['학생1', '학생2']
print(df)

     나이 성별   학교
학생1  15  남  덕영중
학생2  17  여  수리중

In [5]:
df.columns = ['연령','남녀','소속']
print(df)

     연령 남녀   소속
학생1  15  남  덕영중
학생2  17  여  수리중

In [8]:
# 행 인덱스 변경: DataFrame객체.rename(index={기존인덱스: 새인덱스})
# 열 인덱스 변경: DataFrame객체.rename(columns={기존이름: 새이름})

import pandas as pd

matrix = [
    [15, '남자', '덕영중'],
    [17, '여', '수리중']
]

df = pd.DataFrame(matrix, index=['준서','예은'], columns=['나이','성별','학교'])
print(df)

    나이  성별   학교
준서  15  남자  덕영중
예은  17   여  수리중

In [10]:
df = df.rename(columns={
    '나이':'연령',
    '성별':'남녀',
    '학교':'소속'
})

print(df)

    연령  남녀   소속
준서  15  남자  덕영중
예은  17   여  수리중

In [ ]:
df = df.rename(index={
    '준서':'학생1',
    '예은':'학생2'
})

    수학  영어   음악   체육
서준  90  98   95  100
우현  80  89   95   90
인아  70  95  100   90

    수학  영어   음악   체육
서준  90  98   95  100
우현  80  89   95   90
인아  70  95  100   90

In [14]:
# 행/열 삭제

# 행 삭제: DataFrame객체.drop(행인덱스 또는 배열, axis=0, axis='index')
# 열 삭제: DataFrame객체.drop(열이름 또는 배열, axis=1, axis='columns')

import pandas as pd

exam_data = {
    '수학' : [ 90,80,70],
    '영어' : [ 98,89,95],
    '음악' : [ 95,95,100],
    '체육' : [ 100,90,90]
}

df = pd.DataFrame(exam_data, index=['서준','우현','인아'])
print(df)
df

    수학  영어   음악   체육
서준  90  98   95  100
우현  80  89   95   90
인아  70  95  100   90

    수학  영어   음악   체육
서준  90  98   95  100
우현  80  89   95   90
인아  70  95  100   90

In [17]:
df2 = df.copy()
df2 = df2.drop('우현')
df2

    수학  영어   음악   체육
서준  90  98   95  100
인아  70  95  100   90

In [18]:
df3 = df.copy()
df3 = df.drop(['우현','인아'])
df3

    수학  영어  음악   체육
서준  90  98  95  100

In [19]:
df3 = df.copy()
df3 = df3.drop(['영어','음악'], axis=1)
df3

    수학   체육
서준  90  100
우현  80   90
인아  70   90

In [20]:
df4 = df.copy()
df4 = df4.drop(['영어','음악'], axis='columns')
df4

    수학   체육
서준  90  100
우현  80   90
인아  70   90

In [21]:
import pandas as pd

exam_data = {
    '수학' : [ 90,80,70],
    '영어' : [ 98,89,95],
    '음악' : [ 95,95,100],
    '체육' : [ 100,90,90]
}

df = pd.DataFrame(exam_data, index=['서준','우현','인아'])
df

    수학  영어   음악   체육
서준  90  98   95  100
우현  80  89   95   90
인아  70  95  100   90

In [22]:
labell = df.loc['서준']
print(labell)

수학     90
영어     98
음악     95
체육    100
Name: 서준, dtype: int64

In [65]:
# 원소 값 변경

import pandas as pd

exam_data = {
    '이름' : ['서준','우현','인아'],
    '수학' : [ 90,80,70],
    '영어' : [ 98,89,95],
    '음악' : [ 95,95,100],
    '체육' : [ 100,90,90]
}

df = pd.DataFrame(exam_data)
df

   이름  수학  영어   음악   체육
0  서준  90  98   95  100
1  우현  80  89   95   90
2  인아  70  95  100   90

In [66]:
df = df.set_index('이름')
df

    수학  영어   음악   체육
이름
서준  90  98   95  100
우현  80  89   95   90
인아  70  95  100   90

In [68]:
df.loc['서준','체육'] = 90
df

    수학  영어   음악  체육
이름
서준  90  98   95  90
우현  80  89   95  90
인아  70  95  100  90

In [72]:
# 행/열 위치 바꾸기

# 행, 열 바꾸기 : DataFrame객체.transpose()

import pandas as pd

exam_data = {
    '이름' : ['서준','우현','인아'],
    '수학' : [ 90,80,70],
    '영어' : [ 98,89,95],
    '음악' : [ 95,95,100],
    '체육' : [ 100,90,90]
}

df = pd.DataFrame(exam_data)
df

   이름  수학  영어   음악   체육
0  서준  90  98   95  100
1  우현  80  89   95   90
2  인아  70  95  100   90

In [73]:
df= df.transpose()
df

      0   1    2
이름   서준  우현   인아
수학   90  80   70
영어   98  89   95
음악   95  95  100
체육  100  90   90